base_model: meta-llama/Llama-2-13b-hf
quantized_model_path: /data/lliu/huffman/models/meta-llama/Llama-2-13b-hf/compressed_hf/run_58
save_path: /data/lliu/huffman/models/meta-llama/Llama-2-13b-hf/ft_layer_by_layer/run_58_1
seqlen: 4096